/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_blacktree_mc_sculpt_plugin_SculptPluginFramework */

#ifndef _Included_network_blacktree_mc_sculpt_plugin_SculptPluginFramework
#define _Included_network_blacktree_mc_sculpt_plugin_SculptPluginFramework
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     network_blacktree_mc_sculpt_plugin_SculptPluginFramework
 * Method:    checkAuthenticatedPlatform
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_network_blacktree_mc_sculpt_plugin_SculptPluginFramework_checkAuthenticatedPlatform
  (JNIEnv *env, jobject obj, jstring str);

/*
 * Class:     network_blacktree_mc_sculpt_plugin_SculptPluginFramework
 * Method:    winApiHook
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_network_blacktree_mc_sculpt_plugin_SculptPluginFramework_winApiHook
  (JNIEnv *env, jobject str);

#ifdef __cplusplus
}
#endif
#endif
